#!/bin/bash

source "$(dirname $0)/utils/list_branches"
source "$(dirname $0)/utils/command_exists"
source "$(dirname $0)/commands/branches"

command="wow-$1"
! command_exists $command && echo "Usage: https://github.com/andrecavallari/git-wow" && exit 1
$command ${@:2}
